### ISSUE TITLE
not works

### ISSUE THREAD

**Issue by compteccharan** [meister03/discord-error-handler#2]

**Comment by compteccharan** [comment]
Huh IT dosen't work

**Comment by compteccharan** [comment]
![image](https://user-images.githubusercontent.com/82565257/132178735-e62d9835-b15c-462e-b960-ea56c6005daf.png)
 it never posts anything and code is fine I made my own mistake but not reporting but in console it is present

**Comment by compteccharan** [comment]
![image](https://user-images.githubusercontent.com/82565257/132178861-d3640ac5-c38a-43ae-aef5-9363d06de76a.png) fix it soon

**Comment by Iinksafe** [comment]
```js
client.on('message', async (message) => {
    // do stuff
})
```
